{{- if .Values.scaling.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.datadog.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  apiKey: {{ .Values.datadog.apiKey }}
  appKey: {{ .Values.datadog.appKey }}
  datadogSite: {{ .Values.datadog.site | default "datadoghq.com" }}
{{- end }}
