{{- if .Values.scaling.enabled -}}
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: vllm-http-scaledobject
  namespace: {{ .Values.namespace }}
spec:
  # The host KEDA will look for in the incoming requests. 
  # This can be the internal service name or external ingress hostname.
  hosts: 
    - vllm-service.{{ .Values.namespace }}.svc.cluster.local
    - localhost
    - localhost:8000
  scaleTargetRef:
    # Points to the deployment we want to scale
    name: vllm-server
    kind: Deployment
    apiVersion: apps/v1
    service: vllm-service
    port: 8000
  replicas:
    min: {{ .Values.scaling.minReplicas }}
    max: {{ .Values.scaling.maxReplicas }}
  scaledownPeriod: {{ .Values.scaling.scaledownPeriod }}
  targetPendingRequests: {{ .Values.scaling.targetPendingRequests }}
{{- end }}
