repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/aquasecurity/tfsec
    rev: v1.28.5
    hooks:
      - id: tfsec

  - repo: https://github.com/terraform-linters/tflint
    rev: v0.50.3
    hooks:
      - id: tflint

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
